### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by lemonpkt** [lemonpkt/IPProject#20]
Need create, read, update, and delete actions to be implimented in a RESTful API. Most likely this will be done for the Project model.

**Comment by H34l0r** [comment]
I have a basic REST API front point end for viewing projects, though it needs to be hooked in with user authentication.

**Comment by lemonpkt** [comment]
User auth can be done via sessions: http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication

**Comment by lemonpkt** [comment]
Completed via pull request #67
