### ISSUE TITLE
Create new header for Login page

### ISSUE THREAD

**Issue by GilliusThunderHead** [lemonpkt/IPProject#25]
We need to create a new header for the login page that has no functionality. We could use base.html as a template however all that is required is just <nav class="navbar navbar-inverse"> as the user should not have any other functionality other than to submit the form once they have filled in their credentials. I know your (Ben) were looking into the css & bootstrap so if you could check out the latest version I pushed a see what you can do that would be great.

**Comment by lemonpkt** [comment]
Closed by mistake, sorry @Little-G

**Comment by lemonpkt** [comment]
Closed by @GilliusThunderHead via pull request #36
