### ISSUE TITLE
Pagination on all projects view

### ISSUE THREAD

**Issue by lemonpkt** [lemonpkt/IPProject#29]
To cover the AJAX part of the assignment spec, only a page worth of projects should be shown at a time. There needs to be an AJAX call to the sever (easiest to do via the RESTful API #20) to retrieve the next page of projects and update the DOM accordingly.

**Comment by H34l0r** [comment]
The code for the all projects view should also work for end client projects #14 and #11

**Comment by lemonpkt** [comment]
This has been superseded by issue #60 and @Little-G's use of AJAX in the registration form.
