### ISSUE TITLE
Constrain on register

### ISSUE THREAD

**Issue by Little-G** [lemonpkt/IPProject#40]
Make a constraint on register after user has already logged in.
The user won't visit the register page after they've already logged in.

**Comment by lemonpkt** [comment]
Thanks for adding an issue! Is this necessary, though? As long as registration logs out the old user and logs in the new user when they submit the form, why does the registration page need to disallow logged in users?

**Comment by GilliusThunderHead** [comment]
I think it's just so someone can't type register into the path and re-register halfway through a session?

Sent from my iPhone

On 9 Oct 2017, at 6:52 pm, Alex Mueller <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for adding an issue! Is this necessary, though? As long as registration logs out the old user and logs in the new user when they submit the form, why does the registration page need to disallow logged in users?

**Comment by Little-G** [comment]
finished in issue #57
